default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "attendance_development") %>

test:
  <<: *default
  database: product_catalog_test

production:
  <<: *default
  database: product_catalog_production
  username: product_catalog
  password: <%= ENV['PRODUCT_CATALOG_DATABASE_PASSWORD'] %>